### ISSUE TITLE
Exception in DependencyListener while building under Gradle 2.4

### ISSUE THREAD

**Issue by peterlitvak** [johndevs/gradle-vaadin-plugin#182]
I get the following exception with the latest version of Gradle and vaading plugin. Any suggestions?
```
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
        [class java.lang.String]
        [class java.net.URI]
        at fi.jasoft.plugin.DependencyListener.addRepositories(DependencyListener.groovy:140)
        at fi.jasoft.plugin.DependencyListener$addRepositories.callStatic(Unknown Source)
        at fi.jasoft.plugin.DependencyListener.afterEvaluate(DependencyListener.groovy:93)
```

**Comment by peterlitvak** [comment]
It is fixed by PR #185

**Comment by peterlitvak** [comment]
hit the wrong button

**Comment by AndriiKotkov** [comment]
I have the same problem.
