### ISSUE TITLE
Can't compile widgetset with any version

### ISSUE THREAD

**Issue by jorgebsa** [johndevs/gradle-vaadin-plugin#199]
To be honest, I am not sure if this is the plugin's fault or something related to Vaadin. I'm bringing this up here, and will also post on Vaadin's forum. Since yesterday, myself and 2 other colleagues haven't been able to compile the widgetset of any of our Vaadin projects. We haven't changed a single line of configurations, so this is very weird. 

Here's the output of ./gradlew clean build --stacktrace --debug, with wrapper 2.5 and vaadin 7.5.4. (I tried the same with different plugin and Vaadin versions, such as 0.9.8 and 7.3.8)

```
14:23:07.699 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/ConstraintViolationImpl.java'
14:23:07.700 [ERROR] [org.gradle.api.Project] Line 30: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.getExecutableReturnValue()
14:23:07.700 [ERROR] [org.gradle.api.Project] Line 30: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.unwrap(Class<U>)
14:23:07.700 [ERROR] [org.gradle.api.Project] Line 30: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.getExecutableParameters()
14:23:07.701 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'javax.validation.executable.ExecutableValidator'
14:23:07.701 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/executable/ExecutableValidator.java'
14:23:07.701 [ERROR] [org.gradle.api.Project] Line 53: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
14:23:07.701 [ERROR] [org.gradle.api.Project] Line 94: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
14:23:07.701 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'com.google.gwt.validation.client.impl.GwtBeanDescriptorImpl'
14:23:07.702 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/GwtBeanDescriptorImpl.java'
14:23:07.702 [ERROR] [org.gradle.api.Project] Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstraintsForConstructor(Class<?>...)
14:23:07.702 [ERROR] [org.gradle.api.Project] Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstrainedConstructors()
14:23:07.702 [ERROR] [org.gradle.api.Project] Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstraintsForMethod(String, Class<?>...)
14:23:07.703 [ERROR] [org.gradle.api.Project] Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstrainedMethods(MethodType, MethodType...)
14:23:07.703 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
14:23:07.703 [ERROR] [org.gradle.api.Project] Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
14:23:07.704 [ERROR] [org.gradle.api.Project] Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
14:23:07.704 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/PropertyDescriptorImpl.java'
14:23:07.704 [ERROR] [org.gradle.api.Project] Line 31: The type PropertyDescriptorImpl must implement the inherited abstract method CascadableDescriptor.getGroupConversions()
14:23:07.704 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'com.google.gwt.validation.client.impl.ConstraintValidatorContextImpl'
14:23:07.704 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/ConstraintValidatorContextImpl.java'
14:23:07.704 [ERROR] [org.gradle.api.Project] Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addPropertyNode(String)
14:23:07.705 [ERROR] [org.gradle.api.Project] Line 39: The type ConstraintValidatorContextImpl<A,T> must implement the inherited abstract method ConstraintValidatorContext.unwrap(Class<T>)
14:23:07.705 [ERROR] [org.gradle.api.Project] Line 112: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderDefinedContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderDefinedContext.addPropertyNode(String)
14:23:07.706 [ERROR] [org.gradle.api.Project] Line 79: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderCustomizableContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderCustomizableContext.addBeanNode()
14:23:07.706 [ERROR] [org.gradle.api.Project] Line 79: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderCustomizableContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderCustomizableContext.addPropertyNode(String)
14:23:07.706 [ERROR] [org.gradle.api.Project] Line 112: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderDefinedContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderDefinedContext.addBeanNode()
14:23:07.706 [ERROR] [org.gradle.api.Project] Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addParameterNode(int)
14:23:07.706 [ERROR] [org.gradle.api.Project] Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addBeanNode()
14:23:07.707 [ERROR] [org.gradle.api.Project] Line 142: The type ConstraintValidatorContextImpl<A,T>.NodeContextBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeContextBuilder.addBeanNode()
14:23:07.707 [ERROR] [org.gradle.api.Project] Line 142: The type ConstraintValidatorContextImpl<A,T>.NodeContextBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeContextBuilder.addPropertyNode(String)
14:23:07.707 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'javax.validation.ParameterNameProvider'
14:23:07.707 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/ParameterNameProvider.java'
14:23:07.707 [ERROR] [org.gradle.api.Project] Line 54: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
14:23:07.708 [ERROR] [org.gradle.api.Project] Line 44: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
14:23:07.709 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'com.google.gwt.validation.client.impl.GwtValidatorContext'
14:23:07.710 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/GwtValidatorContext.java'
14:23:07.710 [ERROR] [org.gradle.api.Project] Line 29: The type GwtValidatorContext must implement the inherited abstract method ValidatorContext.parameterNameProvider(ParameterNameProvider)
14:23:07.712 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'com.google.gwt.validation.client.impl.PropertyDescriptorImpl'
14:23:07.713 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/PropertyDescriptorImpl.java'
14:23:07.713 [ERROR] [org.gradle.api.Project] Line 31: The type PropertyDescriptorImpl must implement the inherited abstract method CascadableDescriptor.getGroupConversions()
14:23:07.713 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
14:23:07.714 [ERROR] [org.gradle.api.Project] Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
14:23:07.714 [ERROR] [org.gradle.api.Project] Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
14:23:07.719 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'com.google.gwt.validation.client.impl.ConstraintDescriptorImpl'
14:23:07.719 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
14:23:07.719 [ERROR] [org.gradle.api.Project] Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
14:23:07.720 [ERROR] [org.gradle.api.Project] Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
14:23:07.720 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'com.google.gwt.validation.client.GwtConstraintValidatorFactory'
14:23:07.720 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/GwtConstraintValidatorFactory.java'
14:23:07.721 [ERROR] [org.gradle.api.Project] Line 26: The type GwtConstraintValidatorFactory must implement the inherited abstract method ConstraintValidatorFactory.releaseInstance(ConstraintValidator<?,?>)
14:23:07.721 [ERROR] [org.gradle.api.Project] Tracing compile failure path for type 'com.google.gwt.validation.client.impl.NodeImpl'
14:23:07.721 [ERROR] [org.gradle.api.Project] Errors in 'jar:file:/Users/jorgesa/.gradle/caches/modules-2/files-2.1/com.vaadin/vaadin-client/7.5.4/c4771c3e1867fdb795e3738ddc8ab01827633891/vaadin-client-7.5.4.jar!/com/google/gwt/validation/client/impl/NodeImpl.java'
14:23:07.726 [ERROR] [org.gradle.api.Project] Line 25: The type NodeImpl must implement the inherited abstract method Path.Node.as(Class<T>)
14:23:07.727 [ERROR] [org.gradle.api.Project] Line 25: The type NodeImpl must implement the inherited abstract method Path.Node.getKind()
14:23:09.298 [ERROR] [org.gradle.api.Project] Aborting compile due to errors in some input files
14:23:14.775 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':vaadinCompileWidgetset'
14:23:14.776 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :vaadinCompileWidgetset FAILED
14:23:14.776 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :vaadinCompileWidgetset (Thread[Daemon worker,5,main]) completed. Took 28.61 secs.
14:23:14.776 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker,5,main]] finished, busy: 38.653 secs, idle: 0.013 secs
14:23:14.785 [ERROR] [org.gradle.BuildExceptionReporter] 
14:23:14.790 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:23:14.790 [ERROR] [org.gradle.BuildExceptionReporter] 
14:23:14.791 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:23:14.792 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':vaadinCompileWidgetset'.
14:23:14.792 [ERROR] [org.gradle.BuildExceptionReporter] > Widgetset failed to compile. See error log above.
14:23:14.796 [ERROR] [org.gradle.BuildExceptionReporter] 
14:23:14.796 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
14:23:14.798 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':vaadinCompileWidgetset'.
14:23:14.799 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
14:23:14.801 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
14:23:14.802 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
14:23:14.803 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
14:23:14.803 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
14:23:14.803 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
14:23:14.803 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
14:23:14.804 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
14:23:14.819 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
14:23:14.819 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
14:23:14.820 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
14:23:14.820 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
14:23:14.820 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
14:23:14.820 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
14:23:14.820 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
14:23:14.820 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
14:23:14.821 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
14:23:14.821 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
14:23:14.821 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
14:23:14.821 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
14:23:14.821 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
14:23:14.822 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
14:23:14.822 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
14:23:14.822 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.Factories$1.create(Factories.java:22)
14:23:14.822 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
14:23:14.823 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
14:23:14.823 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
14:23:14.823 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
14:23:14.823 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
14:23:14.823 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
14:23:14.824 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
14:23:14.824 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
14:23:14.825 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
14:23:14.828 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
14:23:14.829 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
14:23:14.829 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
14:23:14.829 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
14:23:14.829 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
14:23:14.829 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
14:23:14.829 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.830 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.util.Swapper.swap(Swapper.java:38)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.831 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
14:23:14.832 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.833 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
14:23:14.833 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
14:23:14.833 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.833 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
14:23:14.834 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.api.GradleException: Widgetset failed to compile. See error log above.
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at fi.jasoft.plugin.tasks.CompileWidgetsetTask.compileLocally(CompileWidgetsetTask.groovy:293)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at fi.jasoft.plugin.tasks.CompileWidgetsetTask.run(CompileWidgetsetTask.groovy:161)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
14:23:14.835 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
14:23:14.836 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
14:23:14.836 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
14:23:14.836 [ERROR] [org.gradle.BuildExceptionReporter]        ... 69 more
14:23:14.836 [ERROR] [org.gradle.BuildExceptionReporter] 
14:23:14.836 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:23:14.836 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
14:23:14.836 [LIFECYCLE] [org.gradle.BuildResultLogger] 
14:23:14.837 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 1 mins 15.849 secs
```

I also tried deleting every Vaadin dependency from .m2 and .gradle and let gradle download them again, but nothing changed. Really have no clue right now

**Comment by christoph-frick** [comment]
please check with `gradle dependencies` if the section `vaadin-client` contains (implicit) deps against any higher version than `javax.validation:validation-api:1.0.0.GA`

**Comment by jorgebsa** [comment]
Thanks for the quick answer. It seems that someone updated the eclipselink dependency version of the project, which included the javax.validation:validation-api:1.1.0.Final dependency. By excluding the validation-api module, i was able to execute the task. I will downgrade the eclipselink version for now.

On a sidenote, Is the validation api version included in vaadin or in the plugin?

**Comment by christoph-frick** [comment]
you can exclude stuff for configurations (at least with gradle 2.4).  e.g. https://github.com/christoph-frick/springboot-groovy-vaadin-starter/blob/master/build.gradle#L86

the validation api is basically enforced by the old gwt version vaadin uses.
