### ISSUE TITLE
gwtSdkFirstInClasspath doesn't have any effect

### ISSUE THREAD

**Issue by kiruSan** [johndevs/gradle-vaadin-plugin#202]
I'm using gradle-vaadin plugin version 0.10.1 and Vaadin 7.5.7. Now I've the problem, that the following exception is thrown during the 'vaadinCompileWidgetset' task:

        java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor has interface org.objectweb.asm.ClassVisitor as super class
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.google.gwt.dev.javac.BytecodeSignatureMaker.visitCompileDependenciesInBytecode(BytecodeSignatureMaker.java:227)
        at com.google.gwt.dev.javac.BytecodeSignatureMaker.getCompileDependencySignature(BytecodeSignatureMaker.java:209)
        at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:166)
        at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:42)
        at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:37)
        at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:114)
        at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:366)
        at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
        at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
        at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
        at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
        at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
        at com.google.gwt.dev.Compiler.run(Compiler.java:206)
        at com.google.gwt.dev.Compiler.run(Compiler.java:158)
        at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
        at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
        at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
        at com.google.gwt.dev.Compiler.main(Compiler.java:127)
        :someProject:vaadinCompileWidgetset FAILED

I googled and found another issue with the same problem (#159) and the proposed solution was to include the following lines:

    vaadin {
        gwt {
            gwtSdkFirstInClasspath = true
        }
    }

Unfortunately that doesn't work.

**Comment by johndevs** [comment]
What compile time dependencies do you have in your project? Would it be possible for you to paste the output of "gradle dependencies" here?

**Comment by kiruSan** [comment]
These are the dependencies listed in the gradle file:

        compile 'javax.servlet:javax.servlet-api:3.1.0'
        // Guice
        compile 'com.google.inject:guice:3.0'
        compile 'com.google.inject.extensions:guice-servlet:3.0'

        // jetty
        compile 'org.eclipse.jetty:jetty-server:9.2.5.v20141112'
        compile 'org.eclipse.jetty:jetty-servlet:9.2.5.v20141112'
        compile 'org.eclipse.jetty:jetty-webapp:9.2.5.v20141112'

        // Vaadin
        compile 'com.vaadin:vaadin-server:7.5.9'
        compile 'com.vaadin:vaadin-client:7.5.9'
        compile 'com.vaadin:vaadin-client-compiled:7.5.9'
        compile 'com.vaadin:vaadin-themes:7.5.9'

        // add-on for vaadin  (available add-ons can be listed by vaadinAddons)
        compile 'org.vaadin.addons:tuning-datefield:0.12.0'
        compile 'org.vaadin.addons:dcharts-widget:1.7.0'

        compile 'org.hibernate:hibernate-entitymanager:4.3.10.Final'

You can finde a simple project here: https://github.com/kiruSan/temp/blob/master/simple-project.zip

The output of "gradle dependencies" is:

    $ ./gradlew dependencies
    Using Gradle Vaadin Plugin 0.10.1
    :dependencies
    
    ------------------------------------------------------------
    Root project
    ------------------------------------------------------------
    
    archives - Configuration for archive artifacts.
    No dependencies
    
    compile - Compile classpath for source set 'main'.
    No dependencies
    
    default - Configuration for default artifacts.
    No dependencies
    
    runtime - Runtime classpath for source set 'main'.
    No dependencies
    
    testCompile - Compile classpath for source set 'test'.
    \--- junit:junit:4.11 FAILED
    
    testRuntime - Runtime classpath for source set 'test'.
    \--- junit:junit:4.11 FAILED
    
    BUILD SUCCESSFUL
    
    Total time: 4.437 secs

**Comment by christoph-frick** [comment]
shouldn't that contain a `vaadin-client` configuration?

**Comment by johndevs** [comment]
The example project provided has the vaadin project as a submodule of the root project so ``gradle dependencies`` won't reveal the dependencies of the submodule, only the dependencies of the root project.

However doing ``./gradlew :someProject:dependencies`` in this case reveals that the correct dependencies has been applied (all the vaadin-* dependencies are there).

I tried compiling the widgetset from the test project with ``./gradlew --info clean :someProject:vaadinCompileWidgetset`` and it compiled fine for me. 

I am currently testing on Linux, and you didn't say what OS you are on?

If you are on Windows you could try to setting 
```
vaadin {
     plugin {
          useClassPathJar false
     }
}
```
and see if it makes a difference?

**Comment by johndevs** [comment]
Looks like the problem was with the classpath jar used on Windows by default. This should now be fixed in the referenced patch set. Until the fix is released turning off **useClassPathJar** should work around the issue if you are not hitting path limits on Windows.

**Comment by kiruSan** [comment]
Thank you for fixing the issue. Your workaround seems to fix it for now.
