### ISSUE TITLE
Widgetset compilation in Grails 3 project

### ISSUE THREAD

**Issue by dawiemalan** [johndevs/gradle-vaadin-plugin#255]
I have a Grails 3 project, consisting of multiple modules. The vaadinUpdateWidgetset task fails with this error:

Execution failed for task ':siteman:vaadinUpdateWidgetset'.
> java.io.FileNotFoundException: C:\Development\spawn\swagger4jaxrs\build\classes\main (Access is denied)

This is a transitive dependency on another module in the same project (it is a Grails plugin), and is not required for the widgetset compilation.

Here is the Vaadin config:

```
vaadin {
    version "$vaadinVersion"
    manageDependencies true
    push true
}

vaadinCompile.manageWidgetset true
vaadinCompile.widgetset 'SitemanWidgetSet'
```

Is there a way to exclude dependencies from the widgetset compilation? Alternatively, is there a way to manually configure the Vaadin dependencies?  You have mentioned managing the vaadin-server configuration manually, but I could not find an example anywhere.

Thank you.

**Comment by johndevs** [comment]
What is the file permissions of C:\Development\spawn\swagger4jaxrs\build\classes\main? Can you manually delete the build folder and re-run the the build?

**Comment by dawiemalan** [comment]
It is on Windows, so permissions should not be the issue. I spent several hours with this problem, and tried everything, including manually deleting that folder. I believe it could be caused by the grails gradle plugin as that is the only difference between a working project and this one.

**Comment by dawiemalan** [comment]
Tested on OSX too, same exception, but the message is 'Is a directory'.

**Comment by johndevs** [comment]
Could you post the stacktrace of that exception (run with --stacktrace)?

**Comment by dawiemalan** [comment]
```
* What went wrong:
Execution failed for task ':siteman:vaadinUpdateWidgetset'.
> java.io.FileNotFoundException: /Users/dawie/projects/spawn/spawn-core-grails/build/classes/main (Is a directory)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':siteman:vaadinUpdateWidgetset'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.UncheckedIOException: java.io.FileNotFoundException: /Users/dawie/projects/spawn/spawn-core-grails/build/classes/main (Is a directory)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:78)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 70 more
Caused by: java.io.FileNotFoundException: /Users/dawie/projects/spawn/spawn-core-grails/build/classes/main (Is a directory)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask$_findInheritsInDependencies_closure4$_closure10$_closure11.doCall(UpdateWidgetsetTask.groovy:146)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask$_findInheritsInDependencies_closure4$_closure10.doCall(UpdateWidgetsetTask.groovy:145)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask$_findInheritsInDependencies_closure4.doCall(UpdateWidgetsetTask.groovy:140)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.findInheritsInDependencies(UpdateWidgetsetTask.groovy:139)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask$_findInheritsInDependencies_closure4$_closure10.doCall(UpdateWidgetsetTask.groovy:143)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask$_findInheritsInDependencies_closure4.doCall(UpdateWidgetsetTask.groovy:140)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.findInheritsInDependencies(UpdateWidgetsetTask.groovy:139)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.getInherits(UpdateWidgetsetTask.groovy:213)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.updateWidgetset(UpdateWidgetsetTask.groovy:91)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.ensureWidgetPresent(UpdateWidgetsetTask.groovy:81)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.ensureWidgetPresent(UpdateWidgetsetTask.groovy:65)
	at fi.jasoft.plugin.tasks.UpdateWidgetsetTask.run(UpdateWidgetsetTask.groovy:61)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	... 77 more
```

**Comment by dawiemalan** [comment]
Thanks John. Still not working for me using 0.11-SNAPSHOT though.

**Comment by dawiemalan** [comment]
Sorry, the issue is back. I tried --refresh-dependencies, but no luck. It does seems to be using latest snapshot:

4:36:10 PM: Executing external task 'build'...
Using Gradle Vaadin Plugin 0.11-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':siteman'.
> Failed to notify project evaluation listener.
   > C:\Development\spawn\swagger4jaxrs\build\classes\main (Access is denied)

I tried on Windows and OSX.

**Comment by dawiemalan** [comment]
Here is a patch with a fix. I was unable to create a pull request.
[patch.diff.zip](https://github.com/johndevs/gradle-vaadin-plugin/files/291669/patch.diff.zip)

**Comment by johndevs** [comment]
@dawiemalan What is the difference between that patch and 828b0ff36e9201e1936b4f72e56b5330360b7565 ?

**Comment by dawiemalan** [comment]
It is the same fix, just an additional location (Util.groovy).
