### ISSUE TITLE
vaadinCompile issue, with vaadin 8 at 1.0 version

### ISSUE THREAD

**Issue by zotona** [johndevs/gradle-vaadin-plugin#286]
Empty widgetset
```
<module>
        <inherits name="com.vaadin.DefaultWidgetSet" />
        <set-configuration-property name="devModeRedirectEnabled" value="true" />
        <set-property name="user.agent" value="ie8,ie9,ie10,gecko1_8,safari" />
        <source path="client" />
        <source path="shared" />
        <collapse-all-properties />
        <set-property name="compiler.useSymbolMaps" value="true" />
</module>
```

```1:53:08.283 [ERROR] [org.gradle.api.Project] An internal compiler exception occurred
01:53:08.283 [ERROR] [org.gradle.api.Project] com.google.gwt.dev.jjs.InternalCompilerException: Error constructing Java AST
01:53:08.284 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.jjs.impl.GwtAstBuilder.translateException(GwtAstBuilder.java:3099)
01:53:08.284 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:352)
01:53:08.284 [ERROR] [org.gradle.api.Project] at org.eclipse.jdt.internal.compiler.ast.AllocationExpression.traverse(AllocationExpression.java:670)
01:53:08.284 [ERROR] [org.gradle.api.Project] at org.eclipse.jdt.internal.compiler.ast.ReturnStatement.traverse(ReturnStatement.java:373)
01:53:08.284 [ERROR] [org.gradle.api.Project] at org.eclipse.jdt.internal.compiler.ast.MethodDeclaration.traverse(MethodDeclaration.java:347)
01:53:08.284 [ERROR] [org.gradle.api.Project] at org.eclipse.jdt.internal.compiler.ast.TypeDeclaration.traverse(TypeDeclaration.java:1379)
01:53:08.284 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.jjs.impl.GwtAstBuilder.process(GwtAstBuilder.java:3058)
01:53:08.285 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater$UnitProcessorImpl.process(CompilationStateBuilder.java:141)
01:53:08.285 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.javac.JdtCompiler$CompilerImpl.process(JdtCompiler.java:384)
01:53:08.285 [ERROR] [org.gradle.api.Project] at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:470)
01:53:08.285 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.javac.JdtCompiler.doCompile(JdtCompiler.java:985)
01:53:08.285 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:339)
01:53:08.285 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:580)
01:53:08.286 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:513)
01:53:08.286 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:499)
01:53:08.286 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:668)
01:53:08.286 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.Precompile.precompile(Precompile.java:255)
01:53:08.286 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.Precompile.precompile(Precompile.java:229)
01:53:08.286 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.Precompile.precompile(Precompile.java:145)
01:53:08.287 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.Compiler.run(Compiler.java:206)
01:53:08.287 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.Compiler.run(Compiler.java:158)
01:53:08.287 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.Compiler$1.run(Compiler.java:120)
01:53:08.287 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
01:53:08.287 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
01:53:08.287 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.Compiler.main(Compiler.java:127)
01:53:08.287 [ERROR] [org.gradle.api.Project] Caused by: java.lang.NullPointerException
01:53:08.288 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.jjs.impl.ReferenceMapper.get(ReferenceMapper.java:99)
01:53:08.288 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.pushNewExpression(GwtAstBuilder.java:2642)
01:53:08.288 [ERROR] [org.gradle.api.Project] at com.google.gwt.dev.jjs.impl.GwtAstBuilder$AstVisitor.endVisit(GwtAstBuilder.java:350)
01:53:08.288 [ERROR] [org.gradle.api.Project] ... 23 more
01:53:08.288 [ERROR] [org.gradle.api.Project] at ByteArrayOutputStream.java(137): new String(buf, 0, count)
01:53:08.288 [ERROR] [org.gradle.api.Project] org.eclipse.jdt.internal.compiler.ast.AllocationExpression
```

**Comment by johndevs** [comment]
Could you try with 1.1.1 if it would work better?

**Comment by zotona** [comment]
Env: gradle 3.2
gradle-vaadin-plugin:1.1.1

```
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/ConstraintViolationImpl.java'
Line 31: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.getExecutableReturnValue()
Line 31: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.getExecutableParameters()
Line 31: The type ConstraintViolationImpl<T> must implement the inherited abstract method ConstraintViolation<T>.unwrap(Class<U>)
Tracing compile failure path for type 'com.google.gwt.validation.client.impl.NodeImpl'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/NodeImpl.java'
Line 25: The type NodeImpl must implement the inherited abstract method Path.Node.as(Class<T>)
Line 25: The type NodeImpl must implement the inherited abstract method Path.Node.getKind()
Tracing compile failure path for type 'com.google.gwt.validation.client.impl.PropertyDescriptorImpl'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/PropertyDescriptorImpl.java'
Line 31: The type PropertyDescriptorImpl must implement the inherited abstract method CascadableDescriptor.getGroupConversions()
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
Tracing compile failure path for type 'com.google.gwt.validation.client.impl.ConstraintDescriptorImpl'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
Tracing compile failure path for type 'com.google.gwt.validation.client.impl.ConstraintValidatorContextImpl'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/ConstraintValidatorContextImpl.java'
Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addPropertyNode(String)
Line 39: The type ConstraintValidatorContextImpl<A,T> must implement the inherited abstract method ConstraintValidatorContext.unwrap(Class<T>)
Line 112: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderDefinedContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderDefinedContext.addPropertyNode(String)
Line 79: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderCustomizableContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderCustomizableContext.addBeanNode()
Line 79: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderCustomizableContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderCustomizableContext.addPropertyNode(String)
Line 112: The type ConstraintValidatorContextImpl<A,T>.NodeBuilderDefinedContextImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeBuilderDefinedContext.addBeanNode()
Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addParameterNode(int)
Line 46: The type ConstraintValidatorContextImpl<A,T>.ConstraintViolationBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.addBeanNode()
Line 142: The type ConstraintValidatorContextImpl<A,T>.NodeContextBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeContextBuilder.addBeanNode()
Line 142: The type ConstraintValidatorContextImpl<A,T>.NodeContextBuilderImpl must implement the inherited abstract method ConstraintValidatorContext.ConstraintViolationBuilder.NodeContextBuilder.addPropertyNode(String)
Tracing compile failure path for type 'javax.validation.executable.ExecutableValidator'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/executable/ExecutableValidator.java'
Line 53: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
Line 94: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
Tracing compile failure path for type 'com.google.gwt.validation.client.GwtConstraintValidatorFactory'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/GwtConstraintValidatorFactory.java'
Line 26: The type GwtConstraintValidatorFactory must implement the inherited abstract method ConstraintValidatorFactory.releaseInstance(ConstraintValidator<?,?>)
Tracing compile failure path for type 'com.google.gwt.validation.client.impl.GwtValidatorContext'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/GwtValidatorContext.java'
Line 29: The type GwtValidatorContext must implement the inherited abstract method ValidatorContext.parameterNameProvider(ParameterNameProvider)
Tracing compile failure path for type 'com.google.gwt.validation.client.impl.GwtBeanDescriptorImpl'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/GwtBeanDescriptorImpl.java'
Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstraintsForConstructor(Class<?>...)
Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstrainedConstructors()
Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstraintsForMethod(String, Class<?>...)
Line 38: The type GwtBeanDescriptorImpl<T> must implement the inherited abstract method BeanDescriptor.getConstrainedMethods(MethodType, MethodType...)
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/ConstraintDescriptorImpl.java'
Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getMessageTemplate()
Line 35: The type ConstraintDescriptorImpl<T> must implement the inherited abstract method ConstraintDescriptor<T>.getValidationAppliesTo()
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/com.google.gwt/gwt-user/2.8.0/518579870499e15531f454f35dca0772d7fa31f7/gwt-user-2.8.0.jar!/com/google/gwt/validation/client/impl/PropertyDescriptorImpl.java'
Line 31: The type PropertyDescriptorImpl must implement the inherited abstract method CascadableDescriptor.getGroupConversions()
Tracing compile failure path for type 'javax.validation.ParameterNameProvider'
Errors in 'jar:file:/Users/abv/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/ParameterNameProvider.java'
Line 54: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
Line 44: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
Aborting compile due to errors in some input files
:fronter:components:vaadinCompile FAILED

FAILURE: Build failed with an exception.```

**Comment by johndevs** [comment]
Ah, now I see where the issue is. 

You are using ``validation-api-1.1.0.Final`` instead of ``javax.validation:validation-api:1.0.0.GA``which GWT requires. There are some solutions to how to solve this in #162, basically you need to exclude whatever is pulling in ``validation-api-1.1.0.Final`` into your client classpath.

**Comment by thomaspp** [comment]
Hello! I think I have a similar issue:

`:vaadinCompileErrors in 'jar:file:/C:/Program%20Files/gradle-4.1/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/executable/ExecutableValidator.java'
Line 53: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
Line 94: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
Tracing compile failure path for type 'javax.validation.ParameterNameProvider'
Errors in 'jar:file:/C:/Program%20Files/gradle-4.1/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/7d49b53caed9bd81d172807c3e096d24f3c57090/validation-api-1.1.0.Final-sources.jar!/javax/validation/ParameterNameProvider.java'
Line 54: No source code is available for type java.lang.reflect.Method; did you forget to inherit a required module?
Line 44: No source code is available for type java.lang.reflect.Constructor<T>; did you forget to inherit a required module?
Aborting compile due to errors in some input files`

By forcing resolutionStrategy.force "javax.validation:validation-api:1.0.0.GA" I can complie but have during the runtime (starting the application) the problem, that the ParameterNameProvider is not available...

My build script is the following:

`buildscript {
	repositories {
	    maven { url "https://plugins.gradle.org/m2/" }
	    maven { url "http://oss.sonatype.org/content/repositories/vaadin-snapshots/" }
	    maven { url "http://maven.vaadin.com/vaadin-addons" }
	}
    
    dependencies {
        classpath("com.devsoap.plugin:gradle-vaadin-plugin:1.2.4")
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE")
    }
}

apply plugin: 'war'
apply plugin: 'java'
apply plugin: 'eclipse-wtp'
apply plugin: 'org.springframework.boot'
apply plugin: 'com.devsoap.plugin.vaadin'

war {
    baseName = test
    version =  '1.0'
    manifest {
        attributes("Implementation-Version": version)
    }
}

vaadin {
    version = '8.1.4'
}

vaadinCompile {
    widgetset = 'TestWidgetset'
    widgetsetGenerator = 'de.test.TestWidgetsetGenerator'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
    compile("org.springframework.boot:spring-boot-starter")
    compile("org.springframework.boot:spring-boot-starter-logging")
    compile("org.springframework.boot:spring-boot-starter-data-jpa")
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("org.springframework.boot:spring-boot-starter-mail")
    compile("org.springframework.boot:spring-boot-starter-thymeleaf")
    compile("org.springframework.boot:spring-boot-loader")
    
    compile("org.mariadb.jdbc:mariadb-java-client:1.5.6")
    compile("org.hsqldb:hsqldb:2.3.3")
    compile("org.hibernate:hibernate-validator:6.0.2.Final")
    compile("org.flywaydb:flyway-core:4.2.0")
    compile("com.zaxxer:HikariCP:2.7.1") 

    compile("org.apache.commons:commons-lang3:3.5")

	compile("com.vaadin:vaadin-compatibility-server:8.1.4")
	compile("com.vaadin:vaadin-compatibility-client:8.1.4") 
	compile("com.vaadin:vaadin-compatibility-client-compiled:8.1.4") 
	compile("com.vaadin:vaadin-compatibility-shared:8.1.4") 
	compile("com.vaadin:vaadin-compatibility-themes:8.1.4") 
	compile("com.vaadin:vaadin-bom:8.1.4") 
	compile("com.vaadin:vaadin-push:8.1.4") 

    compile("com.vaadin:vaadin-spring-boot-starter:2.0.1")
    compile("org.vaadin.addons:vaadin-combobox-multiselect:2.0.1")
    compile("org.vaadin.addons:vaadin-grid-util:2.1.0")
    compile("org.vaadin.addons:fontawesomelabel:1.3.4")
    compile("org.vaadin:viritin:2.0.beta2")
}

springBoot {
    mainClass = "de.test.Application"
}

`
