### ISSUE TITLE
Using Widgetset CDN behind HTTP Proxy

### ISSUE THREAD

**Issue by canthony** [johndevs/gradle-vaadin-plugin#310]
I'd like to try using the CDN - but it doesn't seem to be working behind a Proxy; it seems that Groovy's RestClient __doesn't__ automatically use the java System Properties http.proxyHost | http.proxyPort | https.proxyHost | http.proxyPort

Could CompileWidgetsetTask be changed to (optionally) specify an http proxy on RestClient? Ideally by using the standard JVN system properties, but allowing us to override by config values on ``vaadinCompile.httpProxy* = ``

As it happens, I don't need proxy authentication, but others might => https://gist.github.com/bryanchug/4172603

FWIW, in my current project external dependencies download fine, which implies that __gradle__ is using the HTTP Proxy (configured via ~/.gradle/gradle.properties
```
systemProp.http.proxyHost=theProxyHostname
systemProp.http.proxyPort=3128
systemProp.http.nonProxyHosts=localhost|artifact-repo|*.hpd.int

systemProp.https.proxyHost=theProxyHostname
systemProp.https.proxyPort=3128
systemProp.https.nonProxyHosts=localhost|artifact-repo|*.hpd.int
```
Here's a stacktrace showing the failure.
```
Execution failed for task ':orion-admin-ui:vaadinCompile'.
> java.net.SocketException: Socket is not connected: connect

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':orion-admin-ui:vaadinCompile'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter
java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:4
)
[...]
Caused by: java.net.SocketException: Socket is not connected: connect
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:549)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.jav
:180)
        at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
        at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1066)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.RESTClient.post(RESTClient.java:141)
        at groovyx.net.http.RESTClient$post.call(Unknown Source)
        at fi.jasoft.plugin.tasks.CompileWidgetsetTask.queryRemoteWidgetset(CompileWidgetsetTask.groovy:368)
        at fi.jasoft.plugin.tasks.CompileWidgetsetTask.compileRemotely(CompileWidgetsetTask.groovy:229)
        at fi.jasoft.plugin.tasks.CompileWidgetsetTask.run(CompileWidgetsetTask.groovy:206)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        ... 75 more
```

**Comment by johndevs** [comment]
Added proxy configurations for widgetset CDN. 

Feature is documented here https://github.com/johndevs/gradle-vaadin-plugin/wiki/Using-Vaadin-CDN
