### ISSUE TITLE
Question: spring boot package type

### ISSUE THREAD

**Issue by cwiejack** [johndevs/gradle-vaadin-plugin#375]
Hi,
I'm new to Gradle and I just started creating a simple spring boot application with Vaadin. 
Without the gradle-vaadin-plugin applied a JAR File is the result of the build. But now activating the plugin I end up with a WAR File. Is there a config switch for this option? I want to have a JAR file as the final build result. 

I already tried to change all of the output folders from src/main/webapp to src/main/resources so that there will not be a webapp directory, but this has no effect.

Could you give me a hint?
Regards
Christian

**Comment by christoph-frick** [comment]
The resulting war can just be run as you are used to the `jar`.  Either rename it or just don't bother.  `java -jar build/libs/app.war` will work as before.  I have given up the battle on this front.

**Comment by johndevs** [comment]
Hi,

Currently the plugin doesn't support jar packaging out-of-the-box, it is something that has been on the TODO list for a while. But, it is fully possible, you just have to set it up manually from build.gradle. 

Here is a example build.gradle that will configure the jar task to become runnable. After executing ``gradle jar`` you can run the application with ``java -jar build/libs/<projectname>.jar``
```groovy
plugins {
    id 'org.springframework.boot' version '1.5.2.RELEASE'
    id 'fi.jasoft.plugin.vaadin' version '1.1.9'
}

configurations {
   // We need a new configuration to host both our runtime depedencies as well as the spring boot dependencies
   clientBootConfiguration
}

dependencies {
   // Configure our custom configuration
   clientBootConfiguration configurations['vaadin-spring-boot']
   clientBootConfiguration configurations.runtime
}

javadoc {
  // Add  custom configuration to the javadoc task so it can compile the javadoc
   classpath += configurations.clientBootConfiguration
}

jar {
   // Include app theme + compiled widget as well as classes into our jar
   from 'src/main/webapp', sourceSets.main.output  
   // Compile theme and widgetset before creating jar
   dependsOn 'vaadinCompile', 'vaadinThemeCompile'
   // Sprinkle some spring boot sugar on the jar to make it runnable
   finalizedBy bootRepackage
}

bootRepackage {
    // Our SpringBootApplication
    mainClass = 'com.example.test.Application'
    // The custom configuration with our dependencies
    customConfiguration 'clientBootConfiguration'
}

```

**Comment by cwiejack** [comment]
Hi John,

thank you for your reply. Unfortunately your script configuration does not work for me. If I use "gradle  build", there is still a war in the output. If I use "gradle jar", a jar file is generated, but it does not start. (perhaps there is another reason for that, I wrote my code with Kotlin an the error message says something about missing main method)

But Christoph mentioned that the war file is executable. That will work for me for now. 

Regards
Christian

**Comment by GithubMood** [comment]
@johndevs hi John,

Sorry for bothering you again.

Your workaround described here helped me to build runnable artifact!
But now I have a problem when I decided to add integration tests to the project.
I am following advises from this article: https://www.petrikainulainen.net/programming/gradle/getting-started-with-gradle-integration-testing/

My integration-test.gradle script looks like this:
```
if (file('src/integrationTest/java').exists()) {
    sourceSets {
        integrationTest {
            java {
                compileClasspath += main.output + test.output
                runtimeClasspath += main.output + test.output
                srcDir file('src/integration-test/java')
            }
            resources.srcDir file('src/integration-test/resources')
        }
    }

    configurations {
        integrationTestCompile.extendsFrom testCompile
        integrationTestRuntime.extendsFrom testRuntime
    }

    task integrationTest(type: Test) {
        testClassesDir = sourceSets.integrationTest.output.classesDir
        classpath = sourceSets.integrationTest.runtimeClasspath
    }

    tasks.withType(Test) {
        reports.html.destination = file("${reporting.baseDir}/${name}")
    }

    check.dependsOn integrationTest
    integrationTest.mustRunAfter test
}
```

I got the exception:
```
15:18:25.106 [main] DEBUG org.springframework.test.context.junit4.SpringJUnit4ClassRunner - SpringJUnit4ClassRunner constructor called with [class com.it.ids.LoginIntegrationTest]
15:18:25.114 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate]
15:18:25.120 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating BootstrapContext using constructor [public org.springframework.test.context.support.DefaultBootstrapContext(java.lang.Class,org.springframework.test.context.CacheAwareContextLoaderDelegate)]
15:18:25.134 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating TestContextBootstrapper for test class [com.it.ids.LoginIntegrationTest] from class [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]
15:18:25.155 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [com.it.ids.AbstractIntegrationTest]: class path resource [com/it/ids/AbstractIntegrationTest-context.xml] does not exist
15:18:25.155 [main] DEBUG org.springframework.test.context.support.AbstractContextLoader - Did not detect default resource location for test class [com.it.ids.AbstractIntegrationTest]: class path resource [com/it/ids/AbstractIntegrationTestContext.groovy] does not exist
15:18:25.156 [main] INFO org.springframework.test.context.support.AbstractContextLoader - Could not detect default resource locations for test class [com.it.ids.AbstractIntegrationTest]: no resource found for suffixes {-context.xml, Context.groovy}.
15:18:25.193 [main] DEBUG org.springframework.test.context.support.ActiveProfilesUtils - Could not find an 'annotation declaring class' for annotation type [org.springframework.test.context.ActiveProfiles] and class [com.it.ids.LoginIntegrationTest]
java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:258)
	at java.lang.Class.isAnnotationPresent(Class.java:3425)
	at org.springframework.core.annotation.AnnotatedElementUtils.isAnnotated(AnnotatedElementUtils.java:272)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.containsNonTestComponent(SpringBootTestContextBootstrapper.java:184)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.getOrFindConfigurationClasses(SpringBootTestContextBootstrapper.java:167)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.processMergedContextConfiguration(SpringBootTestContextBootstrapper.java:133)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:409)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildMergedContextConfiguration(AbstractTestContextBootstrapper.java:305)
	at org.springframework.test.context.support.AbstractTestContextBootstrapper.buildTestContext(AbstractTestContextBootstrapper.java:112)
	at org.springframework.boot.test.context.SpringBootTestContextBootstrapper.buildTestContext(SpringBootTestContextBootstrapper.java:78)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:120)
	at org.springframework.test.context.TestContextManager.<init>(TestContextManager.java:105)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTestContextManager(SpringJUnit4ClassRunner.java:152)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.<init>(SpringJUnit4ClassRunner.java:143)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:36)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

I solve that exception during gradle build by adding few lines:
```
integrationTest {
    classpath += configurations.clientBootConfiguration
}
```

But I got that exception when I run integration test from Intellij Idea.

Could you please advise how to solve this issue?

**Comment by johndevs** [comment]
I haven't seen that exception before but if it is working when running gradle from the command line then the problem is most likely in how Intellij's Gradle integration is handling the classpath. There is not much the Gradle Vaadin plugin can do about that I'm afraid. 

Since Intellij's own Gradle integration is not that great, I would suggest to instead use the ``idea`` Gradle plugin (add the **idea** plugin to your plugins block) and run the *idea*-task to configure the project for Intellij. If you use that then you can add your custom configuration to IDEA's classpath by adding:
```
idea.module.scopes.TEST.plus += [configurations.clientBootConfiguration]
```
That could possibly solve that issue with the missing annotation.
