### ISSUE TITLE
vaadinCompile fails with the following

### ISSUE THREAD

**Issue by jollyblade** [johndevs/gradle-vaadin-plugin#427]
Hi, 

I just updated to 1.2, changed nothing in build config, everything was fine before, now it doens't work:

Best regards, 

BUILD FAILED in 6s
Exception in thread "Thread-17" Exception in thread "Thread-16" groovy.lang.MissingPropertyException: Could not get unknown property 'codeserverProcess' for task ':cm-gui:vaadinSuperDevMode' of type com.devsoap.plugin.tasks.SuperDevModeTask.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at com.devsoap.plugin.tasks.SuperDevModeTask_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:312)
	at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:306)
	at groovy.lang.Closure.getProperty(Closure.java:295)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at com.devsoap.plugin.tasks.SuperDevModeTask$_closure1.doCall(SuperDevModeTask.groovy:55)
	at com.devsoap.plugin.tasks.SuperDevModeTask$_closure1.doCall(SuperDevModeTask.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-15" groovy.lang.MissingPropertyException: Could not get unknown property 'devModeProcess' for task ':cm-gui:vaadinDevMode' of type com.devsoap.plugin.tasks.DevModeTask.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at com.devsoap.plugin.tasks.DevModeTask_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:312)
	at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:306)
	at groovy.lang.Closure.getProperty(Closure.java:295)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at com.devsoap.plugin.tasks.DevModeTask$_closure1.doCall(DevModeTask.groovy:56)
	at com.devsoap.plugin.tasks.DevModeTask$_closure1.doCall(DevModeTask.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.lang.Thread.run(Thread.java:745)
groovy.lang.MissingPropertyException: Could not get unknown property 'serverInstance' for task ':cm-gui:vaadinRun' of type com.devsoap.plugin.tasks.RunTask.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
	at com.devsoap.plugin.tasks.RunTask_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at groovy.lang.Closure.getPropertyTryThese(Closure.java:312)
	at groovy.lang.Closure.getPropertyOwnerFirst(Closure.java:306)
	at groovy.lang.Closure.getProperty(Closure.java:295)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at com.devsoap.plugin.tasks.RunTask$_closure1.doCall(RunTask.groovy:61)
	at com.devsoap.plugin.tasks.RunTask$_closure1.doCall(RunTask.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at groovy.lang.Closure.call(Closure.java:414)
	at groovy.lang.Closure.call(Closure.java:408)
	at groovy.lang.Closure.run(Closure.java:495)
	at java.lang.Thread.run(Thread.java:745)

**Comment by johndevs** [comment]
Looks like the cleanup threads can't access the private variables (a Groovy feature :D) and will throw an exception when the task has executed. 

However, the tasks should still work, but will throw that at the end (and most likely not clean up the server instances). I'll fix the cleanup threads for the next maintenance release.

**Comment by jollyblade** [comment]
Hi, thank you for the quick reply, the beta1 version works.
