### ISSUE TITLE
Cannot cast object 'com.devsoap.plugin.extensions.TestBenchExtension_Decorated@66b6648e' with class 'com.devsoap.plugin.extensions.TestBenchExtension_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'

### ISSUE THREAD

**Issue by wodencafe** [johndevs/gradle-vaadin-plugin#434]
Hello all, 

we just recently upgraded to Gradle Vaadin Plugin 1.2.0, when we try to run a build using this version, we get this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Cannot cast object 'com.devsoap.plugin.extensions.TestBenchExtension_Decorated@6f0380' with class 'com.devsoap.plugin.extensions.TestBenchExtension_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'com.devsoap.plugin.extensions.TestBenchExtension_Decorated@6f0380' with class 'com.devsoap.plugin.extensions.TestBenchExtension_Decorated' to class 'fi.jasoft.plugin.configuration.TestBenchConfiguration'
        at fi.jasoft.plugin.TaskListener.configureTest(TaskListener.groovy:220)
        at fi.jasoft.plugin.TaskListener.beforeExecute(TaskListener.groovy:65)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
        at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
        at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
        at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy62.beforeExecute(Unknown Source)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:238)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:235)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:224)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:121)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:102)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:96)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:612)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:567)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:96)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

```

**Comment by wodencafe** [comment]
Why is the code mixing both the new classpath com.devsoap with the old classpath fi.jasoft?

**Comment by johndevs** [comment]
This will happen if you are applying both plugins to your project. Please check your build and ensure that you are not applying different plugins in the project and its submodules.

The issue occurs when the plugin tries to add the configuration extensions to the build. Even if you are not using Testbench for example, the configuration extension is always applied.

**Comment by wodencafe** [comment]
Hi @johndevs ,

Thank you for the info, after looking at our projects I found it was because a separate project in our multi-project build was using the old version of the plugin.

So just for clarification, in a multi-project build like this:

```
L- master
L- vaadinproj1
L- vaadinproj2
```

the 2 vaadin projects must be using the same version of the gradle vaadin plugin, for them both to be built in the full build?

**Comment by johndevs** [comment]
> the 2 vaadin projects must be using the same version of the gradle vaadin plugin, for them both to be built in the full build?

Yes, that is right, all projects in the same build should use the same plugin version, otherwise you will get classpath conflicts when the build is evaluated.

**Comment by wodencafe** [comment]
Thank you for assisting us with this, we will use the latest version of this plugin in all of our vaadin projects to stay consistent and avoid these kinds of errors.
