### ISSUE TITLE
vaadinAddons fails on addons with direct file dependency

### ISSUE THREAD

**Issue by peterl1084** [johndevs/gradle-vaadin-plugin#440]
Having declared an addon as a file dependency in your Gradle build like this:

compile files("path/to/addon/addon.1.0.0.jar")

fails with vaadinAddons target as follows:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'aquarius'.
> Cannot get property 'moduleVersion' on null object

This effectively disallows using addons which are hosted only locally as files, rather than "real" dependencies.

`Caused by: java.lang.NullPointerException: Cannot get property 'moduleVersion' on null object
        at com.devsoap.plugin.Util$_memoizedMethodPriv_getResolvedArtifactVersionProjectStringString_closure10$_closure60.doCall(Util.groovy:679)
        at com.devsoap.plugin.Util$_memoizedMethodPriv_getResolvedArtifactVersionProjectStringString_closure10.doCall(Util.groovy:677)
        at com.devsoap.plugin.Util.memoizedMethodPriv$getResolvedArtifactVersionProjectStringString(Util.groovy:675)
        at com.devsoap.plugin.Util$__clinit__closure39.doCall(Util.groovy)
        at com.devsoap.plugin.Util.getResolvedArtifactVersion(Util.groovy)
        at com.devsoap.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12$_closure63$_closure64$_closure65.doCall(Util.groovy:757)
        at com.devsoap.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12$_closure63$_closure64.doCall(Util.groovy:739)
        at com.devsoap.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12$_closure63.doCall(Util.groovy:737)
        at com.devsoap.plugin.Util$_memoizedMethodPriv_findAddonsInProjectProjectStringBooleanList_closure12.doCall(Util.groovy:729)
        at com.devsoap.plugin.Util.memoizedMethodPriv$findAddonsInProjectProjectStringBooleanList(Util.groovy:728)
        at com.devsoap.plugin.Util$__clinit__closure41.doCall(Util.groovy)
        at com.devsoap.plugin.Util.findAddonsInProject(Util.groovy)
        at com.devsoap.plugin.Util.findAddonsInProject(Util.groovy:723)
        at com.devsoap.plugin.Util$findAddonsInProject$10.callStatic(Unknown Source)
        at com.devsoap.plugin.Util.memoizedMethodPriv$resolveWidgetsetFileProject(Util.groovy:981)
        at com.devsoap.plugin.Util$__clinit__closure48.doCall(Util.groovy)
        at com.devsoap.plugin.Util.resolveWidgetsetFile(Util.groovy)
        at com.devsoap.plugin.Util$resolveWidgetsetFile$6.callStatic(Unknown Source)
        at com.devsoap.plugin.Util.memoizedMethodPriv$getWidgetsetProject(Util.groovy:934)
        at com.devsoap.plugin.Util$__clinit__closure47.doCall(Util.groovy)
        at com.devsoap.plugin.Util.getWidgetset(Util.groovy)
        at com.devsoap.plugin.Util$getWidgetset$5.call(Unknown Source)
        at com.devsoap.plugin.GradleVaadinPlugin$_applyDependencies_closure7$_closure28.doCall(GradleVaadinPlugin.groovy:355)`

**Comment by johndevs** [comment]
Hi,

What you want to do is first make the path to the addon a repository and then give a version to the addon you are referencing. That is the recommendation anyhow.

Should look something like this:

```gradle
repositories {
        flatDir {
            dirs "path/to/addon/"
        }
}
depedencies {
       compile name: 'addon', version: '1.0.0'
}
```

That should work for any dependency as long as it uses sane filenames. Usually you'll have some "lib" directory you place all your jar artifacts in anyway.

But, I'll have a look if I can improve that exception somehow when there is no version defined for a dependency. At least it should warn something rather than throw.
