### ISSUE TITLE
gradle-vaadin-plugin adds deps on gretty classpath including old validation API

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#501]
When I apply both the gretty plugin and the gradle-vaadin-plugin, suddenly the gretty's classpath is populated with Vaadin stuff:

```
gretty
+--- com.vaadin:vaadin-client-compiled:8.3.0
+--- com.vaadin:vaadin-client:8.3.0
|    +--- com.vaadin:vaadin-shared:8.3.0
|    +--- com.vaadin:vaadin-server:8.3.0
|    |    +--- com.vaadin:vaadin-sass-compiler:0.9.13
|    |    |    +--- org.w3c.css:sac:1.3
|    |    |    \--- com.vaadin.external.flute:flute:1.3.0.gg2
|    |    +--- com.vaadin:vaadin-shared:8.3.0
|    |    +--- org.jsoup:jsoup:1.11.2
|    |    \--- com.vaadin.external:gentyref:1.2.0.vaadin1
|    \--- com.google.gwt:gwt-elemental:2.8.2
|         \--- com.google.gwt:gwt-user:2.8.2
|              +--- com.google.jsinterop:jsinterop-annotations:1.0.2
|              +--- javax.validation:validation-api:1.0.0.GA
|              +--- javax.servlet:javax.servlet-api:3.1.0
|              \--- org.w3c.css:sac:1.3
+--- com.vaadin:vaadin-client-compiler:8.3.0
|    +--- com.vaadin:vaadin-client:8.3.0 (*)
|    +--- com.google.gwt:gwt-dev:2.8.2
|    |    +--- com.google.code.findbugs:jsr305:1.3.9
|    |    +--- com.google.code.gson:gson:2.6.2
|    |    +--- org.ow2.asm:asm:5.0.3
|    |    +--- org.ow2.asm:asm-util:5.0.3
|    |    |    \--- org.ow2.asm:asm-tree:5.0.3
|    |    |         \--- org.ow2.asm:asm:5.0.3
|    |    +--- org.ow2.asm:asm-commons:5.0.3
|    |    |    \--- org.ow2.asm:asm-tree:5.0.3 (*)
|    |    +--- colt:colt:1.2.0
|    |    +--- ant:ant:1.6.5
|    |    +--- commons-collections:commons-collections:3.2.2
|    |    +--- commons-io:commons-io:2.4
|    |    +--- com.ibm.icu:icu4j:50.1.1
|    |    +--- tapestry:tapestry:4.0.2
|    |    +--- net.sourceforge.htmlunit:htmlunit:2.19
|    |    |    +--- xalan:xalan:2.7.2
|    |    |    |    \--- xalan:serializer:2.7.2
|    |    |    |         \--- xml-apis:xml-apis:1.3.04 -> 1.4.01
|    |    |    +--- commons-collections:commons-collections:3.2.1 -> 3.2.2
|    |    |    +--- org.apache.commons:commons-lang3:3.4
|    |    |    +--- org.apache.httpcomponents:httpclient:4.5.1
|    |    |    |    +--- org.apache.httpcomponents:httpcore:4.4.3
|    |    |    |    +--- commons-logging:commons-logging:1.2
|    |    |    |    \--- commons-codec:commons-codec:1.9 -> 1.10
|    |    |    +--- org.apache.httpcomponents:httpmime:4.5.1
|    |    |    |    \--- org.apache.httpcomponents:httpclient:4.5.1 (*)
|    |    |    +--- commons-codec:commons-codec:1.10
|    |    |    +--- net.sourceforge.htmlunit:htmlunit-core-js:2.17
|    |    |    +--- xerces:xercesImpl:2.11.0
|    |    |    |    \--- xml-apis:xml-apis:1.4.01
|    |    |    +--- net.sourceforge.nekohtml:nekohtml:1.9.22
|    |    |    +--- net.sourceforge.cssparser:cssparser:0.9.18
|    |    |    |    \--- org.w3c.css:sac:1.3
|    |    |    +--- commons-io:commons-io:2.4
|    |    |    +--- commons-logging:commons-logging:1.2
|    |    |    \--- org.eclipse.jetty.websocket:websocket-client:9.2.13.v20150730
|    |    |         +--- org.eclipse.jetty:jetty-util:9.2.13.v20150730 -> 9.2.14.v20151106
|    |    |         +--- org.eclipse.jetty:jetty-io:9.2.13.v20150730 -> 9.2.14.v20151106
|    |    |         |    \--- org.eclipse.jetty:jetty-util:9.2.14.v20151106
|    |    |         \--- org.eclipse.jetty.websocket:websocket-common:9.2.13.v20150730
|    |    |              +--- org.eclipse.jetty.websocket:websocket-api:9.2.13.v20150730
|    |    |              +--- org.eclipse.jetty:jetty-util:9.2.13.v20150730 -> 9.2.14.v20151106
|    |    |              \--- org.eclipse.jetty:jetty-io:9.2.13.v20150730 -> 9.2.14.v20151106 (*)
|    |    +--- org.eclipse.jetty:jetty-webapp:9.2.14.v20151106
|    |    |    +--- org.eclipse.jetty:jetty-xml:9.2.14.v20151106
|    |    |    |    \--- org.eclipse.jetty:jetty-util:9.2.14.v20151106
|    |    |    \--- org.eclipse.jetty:jetty-servlet:9.2.14.v20151106
|    |    |         \--- org.eclipse.jetty:jetty-security:9.2.14.v20151106
|    |    |              \--- org.eclipse.jetty:jetty-server:9.2.14.v20151106
|    |    |                   +--- javax.servlet:javax.servlet-api:3.1.0
|    |    |                   +--- org.eclipse.jetty:jetty-http:9.2.14.v20151106
|    |    |                   |    \--- org.eclipse.jetty:jetty-util:9.2.14.v20151106
|    |    |                   \--- org.eclipse.jetty:jetty-io:9.2.14.v20151106 (*)
|    |    +--- org.eclipse.jetty:jetty-servlets:9.2.14.v20151106
|    |    |    +--- org.eclipse.jetty:jetty-continuation:9.2.14.v20151106
|    |    |    +--- org.eclipse.jetty:jetty-http:9.2.14.v20151106 (*)
|    |    |    +--- org.eclipse.jetty:jetty-util:9.2.14.v20151106
|    |    |    \--- org.eclipse.jetty:jetty-io:9.2.14.v20151106 (*)
|    |    +--- org.eclipse.jetty:jetty-annotations:9.2.14.v20151106
|    |    |    +--- org.eclipse.jetty:jetty-plus:9.2.14.v20151106
|    |    |    |    +--- org.eclipse.jetty:jetty-webapp:9.2.14.v20151106 (*)
|    |    |    |    \--- org.eclipse.jetty:jetty-jndi:9.2.14.v20151106
|    |    |    |         \--- org.eclipse.jetty:jetty-util:9.2.14.v20151106
|    |    |    +--- org.eclipse.jetty:jetty-webapp:9.2.14.v20151106 (*)
|    |    |    +--- javax.annotation:javax.annotation-api:1.2
|    |    |    +--- org.ow2.asm:asm:5.0.1 -> 5.0.3
|    |    |    \--- org.ow2.asm:asm-commons:5.0.1 -> 5.0.3 (*)
|    |    \--- org.eclipse.jetty:apache-jsp:9.2.14.v20151106
|    |         +--- org.eclipse.jetty:jetty-util:9.2.14.v20151106
|    |         +--- org.eclipse.jetty:jetty-server:9.2.14.v20151106 (*)
|    |         +--- org.eclipse.jetty.toolchain:jetty-schemas:3.1.M0
|    |         +--- javax.servlet:javax.servlet-api:3.1.0
|    |         \--- org.mortbay.jasper:apache-jsp:8.0.9.M3
|    |              +--- org.eclipse.jetty.toolchain:jetty-schemas:3.1.M0
|    |              \--- org.mortbay.jasper:apache-el:8.0.9.M3
|    \--- com.vaadin:vaadin-sass-compiler:0.9.13 (*)
\--- javax.validation:validation-api:1.0.0.GA
```

Especially problematic is the `validation-api:1.0.0.GA` which collides with `validation-api` 2.0 and causes Hibernate validator to fail to initialize with:

```
Caused by: java.lang.NoSuchMethodError: javax.validation.spi.ConfigurationState.getParameterNameProvider()Ljavax/validation/ParameterNameProvider;
        at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:151)
        at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
        at org.hibernate.validator.internal.engine.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:322)
        at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:111)
```

If I comment out the gradle-vaadin-plugin, the gretty dependency classpath stays empty.

**Comment by mvysny** [comment]
To reproduce the issue, just clone https://github.com/mvysny/vok-helloword-app the `complete` branch. Currently, vaadin-gradle-plugin is commented out and it can be verified that gretty's classpath is empty, by running `./gradlew web:dependencies`

However, if you uncomment `web/build.gradle:4` and re-run `./gradlew web:dependencies`, the gretty's classpath is suddenly populated with vaadin stuff. Moreover, if you run the app via `./gradlew web:appRun` then it will eventually fail when you try to create a new article.

**Comment by mvysny** [comment]
I tried `manageDependencies false` as a workaround, it didn't help.

**Comment by mvysny** [comment]
Seems to be fixed by using the next Gretty version: the `org.gretty:2.1.0` plugin.
