### ISSUE TITLE
Could not find method logging() for arguments [true] on task ':vaadinCompile' of type 

### ISSUE THREAD

**Issue by mirkoliver** [johndevs/gradle-vaadin-plugin#504]
When trying to configure the compile task and refreshing the project (via Eclipse Buildship) an exception is thrown:

`Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method logging() for arguments [true] on task ':vaadinCompile' of type com.devsoap.plugin.tasks.CompileWidgetsetTask.
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:179)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:89)
	at build_dd4eux7ye637iwk9ag97v82x3$_run_closure6.doCall(C:\Mirko\EclipseSpringWorkspace\sokuware\build.gradle:153)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:136)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:638)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:90)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
	at org.gradle.api.internal.DefaultNamedDomainObjectCollection$ContainerElementsDynamicObject.tryInvokeMethod(DefaultNamedDomainObjectCollection.java:369)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:134)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
	at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:83)
	at build_dd4eux7ye637iwk9ag97v82x3.run(C:\Mirko\EclipseSpringWorkspace\sokuware\build.gradle:138)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 94 more
`

**Comment by johndevs** [comment]
Looks like the wiki is not up-to date. You can use 
```
vaadinCompile {
     logEnabled = true
}
```
instead.

**Comment by mirkoliver** [comment]
With "=" it worked better. Thank you.
