### ISSUE TITLE
vaadinRun fails with exception

### ISSUE THREAD

**Issue by udimu** [johndevs/gradle-vaadin-plugin#512]
I not able to start glassfish server.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinRun'.
> Server process terminated with exit code 1. See build/logs/payara.log for further details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings
```
payara.log

```
[INFO] Listening for transport dt_socket at address: 8000
[ERROR] Apr 21, 2018 11:36:25 PM org.springsource.loaded.agent.SpringLoadedPreProcessor preProcess
[ERROR] SEVERE: Unexpected problem transforming call sites
[ERROR] java.lang.IllegalArgumentException
[ERROR] at sl.org.objectweb.asm.ClassReader.<init>(Unknown Source)
[ERROR] at sl.org.objectweb.asm.ClassReader.<init>(Unknown Source)
[ERROR] at org.springsource.loaded.MethodInvokerRewriter.rewrite(MethodInvokerRewriter.java:345)
[ERROR] at org.springsource.loaded.MethodInvokerRewriter.rewrite(MethodInvokerRewriter.java:99)
[ERROR] at org.springsource.loaded.TypeRegistry.methodCallRewriteUseCacheIfAvailable(TypeRegistry.java:1002)
[ERROR] at org.springsource.loaded.agent.SpringLoadedPreProcessor.preProcess(SpringLoadedPreProcessor.java:361)
[ERROR] at org.springsource.loaded.agent.ClassPreProcessorAgentAdapter.transform(ClassPreProcessorAgentAdapter.java:107)
[ERROR] at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
[ERROR] at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
[ERROR] at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:550)
[ERROR] at java.base/java.lang.ClassLoader.defineClass2(Native Method)
[ERROR] at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1099)
[ERROR] at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
[ERROR] at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:760)
[ERROR] at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:681)
[ERROR] at java.base/jdk.internal.loader.BuiltinClassLoader.findClass(BuiltinClassLoader.java:562)
[ERROR] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:608)
[ERROR] at java.base/java.lang.Class.forName(Class.java:448)
[ERROR] at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:847)
[ERROR] at java.base/java.util.ServiceLoader.access$600(ServiceLoader.java:390)
[ERROR] at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1071)
[ERROR] at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1294)
[ERROR] at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1379)
[ERROR] at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:76)
[ERROR] at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:73)
[ERROR] at java.base/java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<init>(CLDRLocaleProviderAdapter.java:73)
[ERROR] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[ERROR] at java.base/java.lang.Class.newInstance(Class.java:558)
[ERROR] at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:176)
[ERROR] at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:279)
[ERROR] at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
[ERROR] at java.base/java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:363)
[ERROR] at java.base/java.text.DateFormatSymbols.getInstance(DateFormatSymbols.java:341)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:4217)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:4081)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2885)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2793)
[ERROR] at java.base/java.util.Formatter.format(Formatter.java:2587)
[ERROR] at java.base/java.util.Formatter.format(Formatter.java:2517)
[ERROR] at java.base/java.lang.String.format(String.java:2747)
[ERROR] at java.logging/java.util.logging.SimpleFormatter.format(SimpleFormatter.java:178)
[ERROR] at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:199)
[ERROR] at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
[ERROR] at java.logging/java.util.logging.Logger.log(Logger.java:979)
[ERROR] at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
[ERROR] at java.logging/java.util.logging.Logger.log(Logger.java:1029)
[ERROR] at com.devsoap.plugin.PayaraServerRunner.main(PayaraServerRunner.java:49)
[ERROR] 
[ERROR] Exception in thread "main" java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Unable to load sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo
[ERROR] at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
[ERROR] at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:849)
[ERROR] at java.base/java.util.ServiceLoader.access$600(ServiceLoader.java:390)
[ERROR] at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1071)
[ERROR] at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1294)
[ERROR] at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1379)
[ERROR] at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:76)
[ERROR] at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:73)
[ERROR] at java.base/java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<init>(CLDRLocaleProviderAdapter.java:73)
[ERROR] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
[ERROR] at java.base/java.lang.Class.newInstance(Class.java:558)
[ERROR] at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:176)
[ERROR] at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:279)
[ERROR] at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
[ERROR] at java.base/java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:363)
[ERROR] at java.base/java.text.DateFormatSymbols.getInstance(DateFormatSymbols.java:341)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:4217)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:4081)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.printDateTime(Formatter.java:2885)
[ERROR] at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2793)
[ERROR] at java.base/java.util.Formatter.format(Formatter.java:2587)
[ERROR] at java.base/java.util.Formatter.format(Formatter.java:2517)
[ERROR] at java.base/java.lang.String.format(String.java:2747)
[ERROR] at java.logging/java.util.logging.SimpleFormatter.format(SimpleFormatter.java:178)
[ERROR] at java.logging/java.util.logging.StreamHandler.publish(StreamHandler.java:199)
[ERROR] at java.logging/java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:95)
[ERROR] at java.logging/java.util.logging.Logger.log(Logger.java:979)
[ERROR] at java.logging/java.util.logging.Logger.doLog(Logger.java:1006)
[ERROR] at java.logging/java.util.logging.Logger.log(Logger.java:1029)
[ERROR] at com.devsoap.plugin.PayaraServerRunner.main(PayaraServerRunner.java:49)
[ERROR] Caused by: java.lang.LinkageError: loader (instance of  jdk/internal/loader/ClassLoaders$PlatformClassLoader): attempted  duplicate class definition for name: "sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo"
[ERROR] at java.base/java.lang.ClassLoader.defineClass2(Native Method)
[ERROR] at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1099)
[ERROR] at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:206)
[ERROR] at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:760)
[ERROR] at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:681)
[ERROR] at java.base/jdk.internal.loader.BuiltinClassLoader.findClass(BuiltinClassLoader.java:562)
[ERROR] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:608)
[ERROR] at java.base/java.lang.Class.forName(Class.java:448)
[ERROR] at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:847)
```

I use java 9.
```
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)
```

Any solution for this problem?

**Comment by johndevs** [comment]
Could you post your build.gradle? 

Looks like you are getting multiple versions of asm in your build classpath.

**Comment by johndevs** [comment]
Looks like this still is an issue.

**Comment by udimu** [comment]
I cannot reproduce this with following configuration:

```
gradle --version


------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.18.0-3-amd64 amd64
```
**build.gradle** file:

```
// Tell Gradle to add Vaadin support
plugins {
  id 'com.devsoap.plugin.vaadin' version '1.4.1'
}
```

I don't have currently java 9.0.4 installed on my computer.
I build simple [HelloWorld](https://github.com/johndevs/gradle-vaadin-plugin/wiki/Getting-Started-on-the-console) application.

**Comment by johndevs** [comment]
This issue only occurs when using JDK9 or above. With JDK8 everything should work fine.

**Comment by digitalkaoz** [comment]
@johndevs i have the same problem on a totally different project. just came here through google.

im running springboot with openjdk11 and get this error when starting with

`mvn spring-boot:run -Dagentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005`

any idea or link you can point me to?

**Comment by szpq0i** [comment]
@digitalkaoz 
Did you succeeded?
