### ISSUE TITLE
Please add support for Gradle 6

### ISSUE THREAD

**Issue by mvysny** [johndevs/gradle-vaadin-plugin#549]
Using the plugin version 1.4.1 with Gradle 6.2 fails with

```
Caused by: org.gradle.api.InvalidUserCodeException: Please use the ObjectFactory.listProperty() method to create a property of type List<T>.
        at org.gradle.api.internal.model.DefaultObjectFactory.property(DefaultObjectFactory.java:153)
        at org.gradle.api.model.ObjectFactory$property.call(Unknown Source)
        at com.devsoap.plugin.extensions.AddonExtension.<init>(AddonExtension.groovy:41)
        at com.devsoap.plugin.extensions.AddonExtension_Decorated.<init>(Unknown Source)
```

**Comment by mvysny** [comment]
Seems to be working properly with Gradle 6.2.1 and Vaadin Gradle plugin 2.0.0.beta2. Thanks!
